import { NextRequest, NextResponse } from "next/server";
import { adminSessionCookie, auditAdminEvent, getAdminBySession } from "@/lib/admin-auth";
import { serviceCredentials, serviceHeaders } from "@/lib/api-user";
import { getAdminOrders } from "@/lib/commerce/orders";
import { extractClientIp } from "@/lib/security";
const allowedStatuses = new Set(["new", "paid", "processing", "packed", "shipped", "delivered", "cancelled", "refunded", "failed", "digital_fulfilled"]);
async function adminFor(request: NextRequest) { const admin = await getAdminBySession(request.cookies.get(adminSessionCookie)?.value); return admin?.role === "ADMIN" && admin.two_factor_required ? admin : null; }
export async function GET(request: NextRequest) { const admin = await adminFor(request); if (!admin) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); if (request.nextUrl.searchParams.get("event") === "address-view") await auditAdminEvent({ adminUserId: admin.id, eventType: "admin_order_address_viewed", ipAddress: extractClientIp(request.headers), userAgent: request.headers.get("user-agent") || "unknown", metadata: { orderId: request.nextUrl.searchParams.get("orderId") } }); return NextResponse.json({ ok: true }); }
export async function PATCH(request: NextRequest) { const admin = await adminFor(request); if (!admin) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const service = serviceCredentials(); if (!service) return NextResponse.json({ error: "Commerce database unavailable." }, { status: 503 }); const body = await request.json().catch(() => ({})) as { action?: string; orderId?: string; status?: string; carrier?: string; trackingNumber?: string; notes?: string }; const headers = serviceHeaders(service); let response: Response | null = null;
  if (body.action === "status" && body.orderId && allowedStatuses.has(String(body.status))) { response = await fetch(`${service.url}/rest/v1/commerce_orders?id=eq.${body.orderId}`, { method: "PATCH", headers, body: JSON.stringify({ fulfillment_status: body.status, updated_at: new Date().toISOString() }) }); if (response.ok) await fetch(`${service.url}/rest/v1/commerce_order_status_history`, { method: "POST", headers, body: JSON.stringify({ order_id: body.orderId, status: body.status, changed_by: admin.id }) }); }
  else if (body.action === "shipping" && body.orderId) response = await fetch(`${service.url}/rest/v1/commerce_fulfillments?order_id=eq.${body.orderId}`, { method: "PATCH", headers, body: JSON.stringify({ carrier: String(body.carrier || "").slice(0, 100), tracking_number: String(body.trackingNumber || "").slice(0, 180), notes: String(body.notes || "").slice(0, 2000), shipped_at: body.trackingNumber ? new Date().toISOString() : null, updated_at: new Date().toISOString() }) });
  else return NextResponse.json({ error: "Unsupported order action." }, { status: 400 });
  if (!response?.ok) return NextResponse.json({ error: "Order update was rejected." }, { status: 422 }); await auditAdminEvent({ adminUserId: admin.id, eventType: `admin_order_${body.action}`, ipAddress: extractClientIp(request.headers), userAgent: request.headers.get("user-agent") || "unknown", metadata: { orderId: body.orderId, status: body.status, trackingChanged: body.action === "shipping" } }); const data = await getAdminOrders(); return NextResponse.json({ ok: true, orders: data.orders }); }
