import { NextRequest, NextResponse } from "next/server";
import { adminSessionCookie, auditAdminEvent, getAdminBySession } from "@/lib/admin-auth";
import { serviceCredentials, serviceHeaders } from "@/lib/api-user";
import { extractClientIp } from "@/lib/security";
import { getExternalPlatforms, safeExternalUrl, type Clips4SaleItem, type ExternalPlatformSettings } from "@/lib/external-platforms";

export async function POST(request: NextRequest) {
  const admin = await getAdminBySession(request.cookies.get(adminSessionCookie)?.value); if (!admin || admin.role !== "ADMIN" || !admin.two_factor_required) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const service = serviceCredentials(); if (!service) return NextResponse.json({ error: "External-platform database unavailable." }, { status: 503 });
  const body = await request.json().catch(() => ({})) as { action?: string; settings?: ExternalPlatformSettings; clip?: Clips4SaleItem }; const headers = serviceHeaders(service, "return=minimal"); let response: Response;
  if (body.action === "save-settings" && body.settings) { const settings = body.settings; const fanslyUrl = safeExternalUrl(settings.fanslyUrl, "fansly.com"); const clipsStoreUrl = safeExternalUrl(settings.clipsStoreUrl, "clips4sale.com"); if (!fanslyUrl || !clipsStoreUrl) return NextResponse.json({ error: "Fansly and Clips4Sale destinations must be valid HTTPS URLs on the expected platform." }, { status: 400 }); response = await fetch(`${service.url}/rest/v1/external_platform_settings?id=eq.primary`, { method: "PATCH", headers, body: JSON.stringify({ fansly_url: fanslyUrl, fansly_enabled: settings.fanslyEnabled, fansly_button_label: settings.fanslyButtonLabel.slice(0, 80), fansly_handle: settings.fanslyHandle.slice(0, 80), fansly_biography: settings.fanslyBiography.slice(0, 4000), fansly_hero_image: settings.fanslyHeroImage.slice(0, 2000), clips_store_url: clipsStoreUrl, clips_button_label: settings.clipsButtonLabel.slice(0, 80), clips_biography: settings.clipsBiography.slice(0, 4000), updated_by: admin.id, updated_at: new Date().toISOString() }) }); }
  else if (body.action === "save-clip" && body.clip) { const clip = body.clip; const productUrl = clip.productUrl ? safeExternalUrl(clip.productUrl, "clips4sale.com") : null; if (clip.productUrl && !productUrl) return NextResponse.json({ error: "The product destination must be a valid Clips4Sale HTTPS URL." }, { status: 400 }); response = await fetch(`${service.url}/rest/v1/clips4sale_items?id=eq.${encodeURIComponent(clip.id)}`, { method: "PATCH", headers, body: JSON.stringify({ title: clip.title.slice(0, 160), description: clip.description.slice(0, 1000), thumbnail_url: clip.thumbnailUrl.slice(0, 2000), duration: clip.duration.slice(0, 20), product_url: productUrl, sort_order: Math.max(1, Math.floor(clip.sortOrder)), published: clip.published, featured: clip.featured, updated_by: admin.id, updated_at: new Date().toISOString() }) }); }
  else return NextResponse.json({ error: "Unsupported external-platform action." }, { status: 400 });
  if (!response.ok) return NextResponse.json({ error: "External-platform update was rejected." }, { status: 422 }); await auditAdminEvent({ adminUserId: admin.id, eventType: "admin_external_platform_updated", ipAddress: extractClientIp(request.headers), userAgent: request.headers.get("user-agent") || "unknown", metadata: { action: body.action, clipId: body.clip?.id } }); const data = await getExternalPlatforms(true); return NextResponse.json({ ok: true, settings: data.settings, clips: data.clips });
}

