import { randomUUID } from "node:crypto";
import { serviceCredentials, serviceHeaders } from "@/lib/api-user";

export type EntitlementType = "AUDIO_DOWNLOAD" | "VIDEO_ACCESS" | "SUBSCRIPTION_ACCESS" | "DIGITAL_PURCHASE" | "LIVE_PREMIUM_ACCESS" | "MERCH_ORDER_ACCESS" | "PAINTING_ORDER_ACCESS" | "PURCHASE_HISTORY_ACCESS" | "PRIVATE_DOWNLOAD" | "PROMOTIONAL_ACCESS" | "ADMIN_GRANTED_ACCESS";
export type EntitlementStatus = "PENDING" | "ACTIVE" | "EXPIRED" | "REVOKED" | "REFUNDED" | "CHARGEBACK_HOLD" | "ADMIN_HOLD";
export type EntitlementRecord = { entitlementId: string; customerId: string; resourceType: EntitlementType; resourceId: string; sourceOrderId: string | null; sourceTransactionId: string | null; orderItemId: string | null; downloadCount: number; status: EntitlementStatus; grantedAt: string; expiresAt: string | null; revokedAt: string | null; environment: string };

function service() { const credentials = serviceCredentials(); if (!credentials) throw new Error("Entitlement storage is not configured."); return credentials; }
function map(row: Record<string, unknown>): EntitlementRecord { return { entitlementId: String(row.id), customerId: String(row.user_id || row.customer_id), resourceType: String(row.resource_type || "DIGITAL_PURCHASE") as EntitlementType, resourceId: String(row.product_id || row.resource_id || ""), sourceOrderId: row.source_order_id ? String(row.source_order_id) : row.order_id ? String(row.order_id) : row.order_item_id ? String(row.order_item_id) : null, sourceTransactionId: row.source_transaction_id ? String(row.source_transaction_id) : null, orderItemId: row.order_item_id ? String(row.order_item_id) : null, downloadCount: Number(row.download_count || 0), status: String(row.status || (row.revoked_at ? "REVOKED" : "ACTIVE")) as EntitlementStatus, grantedAt: String(row.granted_at || row.created_at), expiresAt: row.expires_at ? String(row.expires_at) : null, revokedAt: row.revoked_at ? String(row.revoked_at) : null, environment: String(row.environment || process.env.XMF_ENVIRONMENT || "LOCAL") }; }

export async function getEntitlement(customerId: string, resourceId: string, resourceType: EntitlementType = "AUDIO_DOWNLOAD") {
  const credentials = service();
  const centralResponse = await fetch(`${credentials.url}/rest/v1/platform_entitlements?customer_id=eq.${encodeURIComponent(customerId)}&resource_id=eq.${encodeURIComponent(resourceId)}&resource_type=eq.${encodeURIComponent(resourceType)}&status=eq.ACTIVE&select=*&limit=1`, { cache: "no-store", headers: serviceHeaders(credentials) }).catch(() => null);
  const centralRows = centralResponse?.ok ? await centralResponse.json() as Array<Record<string, unknown>> : [];
  const legacyResponse = centralRows.length ? null : await fetch(`${credentials.url}/rest/v1/purchase_entitlements?user_id=eq.${encodeURIComponent(customerId)}&product_id=eq.${encodeURIComponent(resourceId)}&revoked_at=is.null&select=*&limit=1`, { cache: "no-store", headers: serviceHeaders(credentials) }).catch(() => null);
  const rows = centralRows.length ? centralRows : legacyResponse?.ok ? await legacyResponse.json() as Array<Record<string, unknown>> : [];
  const [row] = rows;
  if (!row) return null;
  const record = map({ ...row, resource_type: resourceType });
  if (record.expiresAt && new Date(record.expiresAt).getTime() <= Date.now()) return { ...record, status: "EXPIRED" as const };
  return record.status === "ACTIVE" ? record : null;
}

export async function assertEntitlement(customerId: string, resourceId: string, resourceType: EntitlementType = "AUDIO_DOWNLOAD") { const record = await getEntitlement(customerId, resourceId, resourceType); if (!record) return { allowed: false as const, code: "ENTITLEMENT_REQUIRED" as const }; return { allowed: true as const, entitlement: record }; }
export async function grantEntitlement(input: { customerId: string; resourceId: string; resourceType: EntitlementType; orderId?: string | null; transactionId?: string | null; expiresAt?: string | null; environment?: string; adminId?: string | null; reason?: string }) { const credentials = service(); const id = randomUUID(); const response = await fetch(`${credentials.url}/rest/v1/platform_entitlements`, { method: "POST", headers: serviceHeaders(credentials, "resolution=merge-duplicates,return=representation"), body: JSON.stringify({ id, customer_id: input.customerId, resource_id: input.resourceId, resource_type: input.resourceType, source_order_id: input.orderId || null, source_transaction_id: input.transactionId || null, status: "ACTIVE", expires_at: input.expiresAt || null, environment: input.environment || process.env.XMF_ENVIRONMENT || "LOCAL", granted_by: input.adminId || null, admin_note: input.reason?.slice(0, 500) || null }) }); if (!response.ok) throw new Error("Entitlement could not be granted."); return id; }
export async function setEntitlementStatus(entitlementId: string, status: Exclude<EntitlementStatus, "PENDING" | "ACTIVE">, reason: string) { const credentials = service(); const response = await fetch(`${credentials.url}/rest/v1/platform_entitlements?id=eq.${encodeURIComponent(entitlementId)}`, { method: "PATCH", headers: serviceHeaders(credentials, "return=minimal"), body: JSON.stringify({ status, revoked_at: ["REVOKED", "REFUNDED", "CHARGEBACK_HOLD"].includes(status) ? new Date().toISOString() : null, admin_note: reason.slice(0, 500), updated_at: new Date().toISOString() }) }); return response.ok; }
