"use client";

import { useI18n } from "@/components/I18nProvider";
import PurchaseItemCard from "@/components/purchase/PurchaseItemCard";
import PurchaseModalShell from "@/components/purchase/PurchaseModalShell";
import { usePurchase } from "@/components/purchase/PurchaseProvider";
import PurchaseSummaryPanel from "@/components/purchase/PurchaseSummaryPanel";

export default function CheckoutModal() {
  const { t } = useI18n();
  const { cartItems, summary, busy, status, errorCode, result, shippingAddress, setShippingAddress, closePurchase, returnToCart, removeProduct, checkout, quoteCheckout, addTokens, viewPurchases } = usePurchase();
  if (result) return <PurchaseModalShell title={t("purchase.completeTitle")} subtitle={t("purchase.completeSubtitle")} onClose={closePurchase}><div className="purchase-success" role="status">
    <span className="purchase-success-mark" aria-hidden="true">✓</span><h3>{t("purchase.completeTitle")}</h3><p>{t("purchase.orderReference", { reference: result.orderNumber || result.orderId.slice(0, 8).toUpperCase() })}</p>
    <dl><div><dt>{t("purchase.items", { count: result.itemCount })}</dt><dd>{result.itemCount}</dd></div><div><dt>{t("purchase.paid")}</dt><dd>{t("audioStore.coins", { count: result.totalCoins })}</dd></div><div><dt>{t("purchase.remainingBalance")}</dt><dd>{t("audioStore.coins", { count: result.tokenBalance })}</dd></div></dl>
    {result.requiresShipping ? <p>{t("purchase.shippingConfirmation", { country: result.shippingCountry || "—" })}</p> : null}<div>{summary.digitalItemCount ? <button className="primary" type="button" onClick={viewPurchases}>{t("purchase.downloadNow")}</button> : null}<button className="secondary" type="button" onClick={viewPurchases}>{result.requiresShipping ? t("purchase.myOrders") : t("purchase.viewPurchases")}</button><button className="secondary" type="button" onClick={closePurchase}>{t("purchase.continueShopping")}</button></div>
  </div></PurchaseModalShell>;

  return <PurchaseModalShell title={t("purchase.checkoutTitle")} subtitle={t("purchase.checkoutSubtitle")} onClose={closePurchase}>
    {cartItems.length ? <><div className="purchase-modal-grid purchase-checkout-grid"><section className="purchase-cart-content"><h3>{t("purchase.yourItems", { count: summary.itemCount })}</h3><div className="purchase-item-list">{cartItems.map((product) => { const lineId = product.cartLineId || product.id; return <PurchaseItemCard key={lineId} product={product} removable onRemove={() => void removeProduct(lineId)} disabled={busy} />; })}</div>
      {summary.requiresShipping ? <fieldset className="purchase-shipping-form"><legend>{t("purchase.shippingAddress")}</legend><label>{t("purchase.fullName")}<input autoComplete="name" required value={shippingAddress.fullName} onChange={(event) => setShippingAddress({ ...shippingAddress, fullName: event.target.value })} /></label><label>{t("purchase.address1")}<input autoComplete="address-line1" required value={shippingAddress.addressLine1} onChange={(event) => setShippingAddress({ ...shippingAddress, addressLine1: event.target.value })} /></label><label>{t("purchase.address2")}<input autoComplete="address-line2" value={shippingAddress.addressLine2} onChange={(event) => setShippingAddress({ ...shippingAddress, addressLine2: event.target.value })} /></label><label>{t("purchase.city")}<input autoComplete="address-level2" required value={shippingAddress.city} onChange={(event) => setShippingAddress({ ...shippingAddress, city: event.target.value })} /></label><label>{t("purchase.region")}<input autoComplete="address-level1" value={shippingAddress.region} onChange={(event) => setShippingAddress({ ...shippingAddress, region: event.target.value })} /></label><label>{t("purchase.postalCode")}<input autoComplete="postal-code" required value={shippingAddress.postalCode} onChange={(event) => setShippingAddress({ ...shippingAddress, postalCode: event.target.value })} /></label><label>{t("purchase.country")}<input autoComplete="country-name" required value={shippingAddress.country} onChange={(event) => setShippingAddress({ ...shippingAddress, country: event.target.value })} /></label><label>{t("purchase.phone")}<input type="tel" autoComplete="tel" value={shippingAddress.phone} onChange={(event) => setShippingAddress({ ...shippingAddress, phone: event.target.value })} /></label><label className="is-wide">{t("purchase.instructions")}<textarea rows={2} value={shippingAddress.instructions} onChange={(event) => setShippingAddress({ ...shippingAddress, instructions: event.target.value })} /></label><p className="is-wide">{t("purchase.customsNotice")}</p></fieldset> : <section className="purchase-download-info" aria-labelledby="purchase-download-title"><h3 id="purchase-download-title">{t("purchase.downloadInfoTitle")}</h3><p>{t("purchase.downloadInfo")}</p></section>}
      <div className="purchase-benefits purchase-checkout-benefits"><span><b>↓</b><strong>{t("purchase.instantDownload")}</strong><small>{t("purchase.instantDownloadNote")}</small></span><span><b>♢</b><strong>{t("purchase.privateSecure")}</strong><small>{t("purchase.entitlementProtected")}</small></span><span><b>▣</b><strong>{t("purchase.anyDevice")}</strong><small>{t("purchase.supportedBehavior")}</small></span><span><b>◉</b><strong>{t("purchase.highQuality")}</strong><small>{t("purchase.highQualityNote")}</small></span></div>
    </section><PurchaseSummaryPanel showPaymentMethod /></div>
      {errorCode ? <div className="purchase-checkout-error" role="alert"><strong>{status || t("audioStore.checkoutFailed")}</strong><span>{t("purchase.noDeduction")}</span><div><button type="button" onClick={() => void (summary.requiresShipping && !summary.quoteReady ? quoteCheckout() : checkout())}>{t("purchase.retry")}</button><button type="button" onClick={returnToCart}>{t("purchase.returnCart")}</button>{errorCode === "INSUFFICIENT_TOKENS" ? <button type="button" onClick={addTokens}>{t("purchase.addTokens")}</button> : null}</div></div> : <p className="purchase-modal-status" role="status" aria-live="polite">{status}</p>}
      <p className="purchase-policy-notice">{t("purchase.termsPrefix")} <a href="/policies#terms" target="_blank" rel="noreferrer">{t("footer.terms")}</a> {t("purchase.termsJoin")} <a href="/policies#refunds" target="_blank" rel="noreferrer">{t("footer.refund")}</a>.</p>
      <footer className="purchase-modal-actions"><button className="secondary" type="button" disabled={busy} onClick={closePurchase}>{t("purchase.cancel")}</button>{summary.requiresShipping && !summary.quoteReady ? <button className="primary purchase-confirm" type="button" disabled={busy} onClick={() => void quoteCheckout()}>{busy ? t("purchase.calculatingQuote") : t("purchase.calculateQuote")}</button> : <button className="primary purchase-confirm" type="button" disabled={busy || !summary.canCheckout} onClick={() => void checkout()}>{busy ? t("audioStore.checkoutProgress") : t("purchase.confirmPay", { count: summary.total })}</button>}</footer>
    </> : <div className="purchase-empty"><h3>{t("purchase.emptyTitle")}</h3><button className="primary" type="button" onClick={returnToCart}>{t("purchase.returnCart")}</button></div>}
  </PurchaseModalShell>;
}
