import { serviceCredentials, serviceHeaders } from "@/lib/api-user";

export type TaxProviderKind = "NONE" | "MANUAL" | "PROVIDER";
export type AccountingProviderKind = "NONE" | "QUICKBOOKS" | "XERO" | "CUSTOM";
export type TaxRecord = { jurisdiction: string | null; taxableAmountMinor: number; taxAmountMinor: number; taxType: string | null; taxRate: number | null; provider: TaxProviderKind; providerReference: string | null; exempt: boolean; transactionDate: string; orderId: string | null };
export interface TaxProvider { readonly kind: TaxProviderKind; calculateTax(input: { amountMinor: number; jurisdiction?: string | null }): Promise<TaxRecord>; validateAddress?(address: Record<string, string>): Promise<{ valid: boolean; jurisdiction: string | null }>; getTaxBreakdown?(input: TaxRecord): Promise<TaxRecord>; }
export class NoTaxProvider implements TaxProvider { readonly kind = "NONE" as const; async calculateTax(input: { amountMinor: number; jurisdiction?: string | null }) { return { jurisdiction: input.jurisdiction || null, taxableAmountMinor: input.amountMinor, taxAmountMinor: 0, taxType: null, taxRate: null, provider: this.kind, providerReference: null, exempt: false, transactionDate: new Date().toISOString(), orderId: null }; } }
export interface AccountingProvider { readonly kind: AccountingProviderKind; exportRecords(input: { rows: Array<Record<string, unknown>>; format: "CSV" | "JSON" }): Promise<{ accepted: boolean; reference: string | null }>; }
export class NoAccountingProvider implements AccountingProvider { readonly kind = "NONE" as const; async exportRecords() { return { accepted: false, reference: null }; } }

export type AccountingSummary = { grossRevenueMinor: number; refundsMinor: number; processorFeesMinor: number; fulfillmentCostsMinor: number; infrastructureCostsMinor: number; otherCostsMinor: number; estimatedOperatingResultMinor: number; taxCollectedMinor: number; pendingFundsMinor: number; settledPayoutsMinor: number; cashAvailableMinor: number | null; categories: Record<string, number>; reconciliationFlags: string[]; taxStatus: "TAX CONFIGURATION REQUIRED" | "CONFIGURED" };
export async function getAccountingSummary(): Promise<AccountingSummary> { const credentials = serviceCredentials(); if (!credentials) return { grossRevenueMinor: 0, refundsMinor: 0, processorFeesMinor: 0, fulfillmentCostsMinor: 0, infrastructureCostsMinor: 0, otherCostsMinor: 0, estimatedOperatingResultMinor: 0, taxCollectedMinor: 0, pendingFundsMinor: 0, settledPayoutsMinor: 0, cashAvailableMinor: null, categories: {}, reconciliationFlags: ["ACCOUNTING DATA SOURCE NOT CONFIGURED"], taxStatus: "TAX CONFIGURATION REQUIRED" }; const headers = serviceHeaders(credentials); const [ledgerResponse, costResponse, payoutResponse] = await Promise.all([fetch(`${credentials.url}/rest/v1/admin_earnings_ledger?select=category,gross_amount_minor,processor_fee_minor,fulfillment_cost_minor,status`, { cache: "no-store", headers }).catch(() => null), fetch(`${credentials.url}/rest/v1/cost_providers?select=category,fixed_monthly,usage_monthly,active&active=eq.true`, { cache: "no-store", headers }).catch(() => null), fetch(`${credentials.url}/rest/v1/admin_earnings_settlements?select=amount_minor,status`, { cache: "no-store", headers }).catch(() => null)]); const ledger = ledgerResponse?.ok ? await ledgerResponse.json() as Array<Record<string, unknown>> : []; const costs = costResponse?.ok ? await costResponse.json() as Array<Record<string, unknown>> : []; const payouts = payoutResponse?.ok ? await payoutResponse.json() as Array<Record<string, unknown>> : []; const categories: Record<string, number> = {}; let gross = 0; let fees = 0; let fulfillment = 0; for (const row of ledger) { const amount = Number(row.gross_amount_minor || 0); gross += amount; fees += Number(row.processor_fee_minor || 0); fulfillment += Number(row.fulfillment_cost_minor || 0); const category = String(row.category || "OTHER"); categories[category] = (categories[category] || 0) + amount; } const infra = costs.reduce((sum, row) => sum + Number(row.fixed_monthly || 0) + Number(row.usage_monthly || 0), 0) * 100; const settled = payouts.filter((row) => String(row.status) === "settled").reduce((sum, row) => sum + Number(row.amount_minor || 0), 0); return { grossRevenueMinor: gross, refundsMinor: 0, processorFeesMinor: fees, fulfillmentCostsMinor: fulfillment, infrastructureCostsMinor: infra, otherCostsMinor: 0, estimatedOperatingResultMinor: gross - fees - fulfillment - infra, taxCollectedMinor: 0, pendingFundsMinor: Math.max(0, gross - settled), settledPayoutsMinor: settled, cashAvailableMinor: null, categories, reconciliationFlags: ledgerResponse?.ok ? [] : ["LEDGER SOURCE UNAVAILABLE"], taxStatus: "TAX CONFIGURATION REQUIRED" }; }
export function accountingCsv(rows: Array<Record<string, unknown>>) { const keys = [...new Set(rows.flatMap((row) => Object.keys(row)))]; return [keys.join(","), ...rows.map((row) => keys.map((key) => JSON.stringify(row[key] ?? "")).join(","))].join("\n"); }
