import { serviceCredentials, serviceHeaders } from "@/lib/api-user";
import type { AuctionBid, PaintingAuction } from "@/lib/auctions/types";

const now = Date.now();
export const fallbackPaintings: PaintingAuction[] = [
  { id: "painting-1", slug: "signal-after-midnight", title: "Signal After Midnight", artist: "Noddy", shortDescription: "An original study in black, white, and electric green.", fullDescription: "An original Noddy painting created for the XMASKEDFREAKS collection. The final listing includes signed authenticity documentation and condition details.", images: ["/backgrounds/matrix-slim-gray/matrix-slim-gray-reference.png"], imageAlt: ["Signal After Midnight painting"], imageCaptions: ["Primary view"], coverImageIndex: 0, dimensions: "24 × 30 in", medium: "Mixed media on canvas", yearCreated: 2026, condition: "Original studio condition", authenticity: "Signed certificate included", currentBid: 240, startingBid: 200, buyNowPrice: 1200, bidCount: 3, bidderCount: 2, startsAt: new Date(now - 3600000).toISOString(), endsAt: new Date(now + 86400000).toISOString(), status: "live", internationalShippingAllowed: true, shippingNotes: "Private fulfillment notes are visible only in ADMIN.", terms: "Winning bids are binding subject to account, wallet, and shipping verification.", antiSnipingEnabled: true, antiSnipingWindowSeconds: 120, antiSnipingExtensionSeconds: 120, antiSnipingMaxExtensions: 5, extensionCount: 0, published: true, featured: true },
  { id: "painting-2", slug: "behind-the-mask", title: "Behind the Mask", artist: "Noddy", shortDescription: "Layered portrait work built around shadow and reflected light.", fullDescription: "An original Noddy work with a dark reflective palette and hand-finished details.", images: ["/backgrounds/matrix-slim-gray/matrix-slim-gray-thumbnail.png"], imageAlt: ["Behind the Mask painting"], imageCaptions: ["Primary view"], coverImageIndex: 0, dimensions: "18 × 24 in", medium: "Acrylic on canvas", yearCreated: 2026, condition: "Original studio condition", authenticity: "Signed certificate included", currentBid: 180, startingBid: 180, buyNowPrice: null, bidCount: 0, bidderCount: 0, startsAt: new Date(now + 43200000).toISOString(), endsAt: new Date(now + 172800000).toISOString(), status: "scheduled", internationalShippingAllowed: true, shippingNotes: "Private fulfillment notes are visible only in ADMIN.", terms: "Bidding opens at the scheduled server time.", antiSnipingEnabled: false, antiSnipingWindowSeconds: 120, antiSnipingExtensionSeconds: 120, antiSnipingMaxExtensions: 0, extensionCount: 0, published: true, featured: false }
];

function mapAuction(row: Record<string, unknown>, includePrivate: boolean): PaintingAuction { const images = Array.isArray(row.images) && row.images.length ? row.images.map(String) : ["/branding/optimized/mask-logo-512.png"]; const rawStatus = String(row.status); return { id: String(row.id), slug: String(row.slug), title: String(row.title), artist: String(row.artist), shortDescription: String(row.short_description || ""), fullDescription: String(row.full_description || ""), images, imageAlt: Array.isArray(row.image_alt) ? row.image_alt.map(String) : images.map(() => String(row.title || "Painting")), imageCaptions: Array.isArray(row.image_captions) ? row.image_captions.map(String) : images.map(() => ""), coverImageIndex: Math.min(images.length - 1, Math.max(0, Number(row.cover_image_index || 0))), dimensions: String(row.dimensions || ""), medium: String(row.medium || ""), yearCreated: row.year_created === null ? null : Number(row.year_created), condition: String(row.condition || ""), authenticity: String(row.authenticity || ""), currentBid: Number(row.current_bid || row.starting_bid || 0), startingBid: Number(row.starting_bid || 0), buyNowPrice: row.buy_now_price === null ? null : Number(row.buy_now_price), bidCount: Number(row.bid_count || 0), bidderCount: Number(row.bidder_count || 0), startsAt: String(row.starts_at), endsAt: String(row.ends_at), status: (rawStatus === "reserve_not_met" ? "unsold" : rawStatus) as PaintingAuction["status"], internationalShippingAllowed: true, shippingNotes: includePrivate ? String(row.shipping_notes || "") : "", terms: String(row.terms || ""), antiSnipingEnabled: Boolean(row.anti_sniping_enabled), antiSnipingWindowSeconds: Number(row.anti_sniping_window_seconds || 120), antiSnipingExtensionSeconds: Number(row.anti_sniping_extension_seconds || 120), antiSnipingMaxExtensions: Number(row.anti_sniping_max_extensions || 0), extensionCount: Number(row.extension_count || 0), published: Boolean(row.is_published), featured: Boolean(row.is_featured) }; }
export async function getPaintingAuctions(includeAll = false) { const service = serviceCredentials(); if (!service) return { configured: false, auctions: fallbackPaintings.map((auction) => includeAll ? auction : { ...auction, shippingNotes: "" }), serverTime: new Date().toISOString() }; const filter = includeAll ? "" : "&is_published=eq.true"; const requestOptions = includeAll ? { cache: "no-store" as const } : { next: { revalidate: 15, tags: ["public:paintings"] } }; const response = await fetch(`${service.url}/rest/v1/painting_auctions?select=*&order=is_featured.desc,ends_at.asc${filter}`, { ...requestOptions, headers: serviceHeaders(service) }).catch(() => null); if (!response?.ok) return { configured: false, auctions: fallbackPaintings.map((auction) => includeAll ? auction : { ...auction, shippingNotes: "" }), serverTime: new Date().toISOString() }; return { configured: true, auctions: (await response.json() as Record<string, unknown>[]).map((row) => mapAuction(row, includeAll)), serverTime: new Date().toISOString() }; }
export async function getAuctionBids(auctionId: string): Promise<AuctionBid[]> { const service = serviceCredentials(); if (!service) return []; const response = await fetch(`${service.url}/rest/v1/painting_bids?auction_id=eq.${auctionId}&select=id,auction_id,bidder_label,amount,created_at,status&order=amount.desc&limit=100`, { cache: "no-store", headers: serviceHeaders(service) }); if (!response.ok) return []; return (await response.json() as Record<string, unknown>[]).map((row) => ({ id: String(row.id), auctionId: String(row.auction_id), bidderLabel: String(row.bidder_label || "Bidder"), amount: Number(row.amount), createdAt: String(row.created_at), status: String(row.status) as AuctionBid["status"] })); }
