import { NextRequest, NextResponse } from "next/server";
import { adminSessionCookie, auditAdminEvent, getAdminBySession } from "@/lib/admin-auth";
import { serviceCredentials, serviceHeaders } from "@/lib/api-user";
import { getPaintingAuctions } from "@/lib/auctions/catalog";
import { extractClientIp } from "@/lib/security";
import type { PaintingAuction } from "@/lib/auctions/types";
const states = new Set(["draft", "scheduled", "live", "extended", "sold", "unsold", "cancelled", "fulfillment_pending", "shipped", "delivered"]);
export async function POST(request: NextRequest) { const admin = await getAdminBySession(request.cookies.get(adminSessionCookie)?.value); if (!admin || admin.role !== "ADMIN" || !admin.two_factor_required) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const service = serviceCredentials(); if (!service) return NextResponse.json({ error: "Auction database unavailable." }, { status: 503 }); const body = await request.json().catch(() => ({})) as { action?: string; auction?: PaintingAuction }; const auction = body.auction; if (!auction || !states.has(auction.status)) return NextResponse.json({ error: "Invalid auction." }, { status: 400 }); const headers = serviceHeaders(service); let response: Response;
  if (body.action?.startsWith("cancel:")) { const reason = body.action.slice(7).trim(); if (reason.length < 5) return NextResponse.json({ error: "A meaningful cancellation reason is required." }, { status: 400 }); response = await fetch(`${service.url}/rest/v1/rpc/cancel_painting_auction`, { method: "POST", headers, body: JSON.stringify({ p_auction_id: auction.id, p_admin_id: admin.id, p_reason: reason }) }); }
  else response = await fetch(`${service.url}/rest/v1/painting_auctions?id=eq.${auction.id}`, { method: "PATCH", headers, body: JSON.stringify({ title: auction.title.slice(0, 160), artist: auction.artist.slice(0, 120), short_description: auction.shortDescription.slice(0, 500), full_description: auction.fullDescription.slice(0, 5000), images: auction.images.slice(0, 8), image_alt: auction.imageAlt.slice(0, 8), image_captions: auction.imageCaptions.slice(0, 8), cover_image_index: Math.max(0, Math.min(auction.coverImageIndex, Math.max(0, auction.images.length - 1))), dimensions: auction.dimensions.slice(0, 120), medium: auction.medium.slice(0, 120), year_created: auction.yearCreated, condition: auction.condition.slice(0, 500), authenticity: auction.authenticity.slice(0, 1000), starting_bid: Math.max(1, Math.floor(auction.startingBid)), reserve_price: null, buy_now_price: auction.buyNowPrice, starts_at: auction.startsAt, ends_at: auction.endsAt, status: auction.status, domestic_shipping: true, international_shipping: true, shipping_notes: auction.shippingNotes.slice(0, 2000), terms: auction.terms.slice(0, 4000), anti_sniping_enabled: auction.antiSnipingEnabled, anti_sniping_window_seconds: Math.max(15, auction.antiSnipingWindowSeconds), anti_sniping_extension_seconds: Math.max(15, auction.antiSnipingExtensionSeconds), anti_sniping_max_extensions: Math.max(0, auction.antiSnipingMaxExtensions), is_published: auction.published, is_featured: auction.featured, updated_by: admin.id, updated_at: new Date().toISOString() }) });
  if (!response.ok) return NextResponse.json({ error: "Auction change rejected." }, { status: 422 }); await auditAdminEvent({ adminUserId: admin.id, eventType: body.action?.startsWith("cancel:") ? "admin_auction_cancelled" : "admin_auction_updated", ipAddress: extractClientIp(request.headers), userAgent: request.headers.get("user-agent") || "unknown", metadata: { auctionId: auction.id, action: body.action } }); const data = await getPaintingAuctions(true); return NextResponse.json({ ok: true, auctions: data.auctions }); }
