import { serviceCredentials, serviceHeaders } from "@/lib/api-user";

export type CostCategory = "DATABASE" | "STORAGE" | "CDN" | "STREAMING" | "EMAIL" | "MEDIA_PROCESSING" | "QUEUE" | "CACHE" | "PAYMENTS" | "PRINTIFY" | "MONITORING" | "BACKUPS" | "HOSTING" | "DOMAIN" | "SECURITY" | "OTHER";
export type CostSource = "MANUAL" | "ESTIMATED" | "PROVIDER_API";
export type CostFrequency = "ONE_TIME" | "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY" | "USAGE_BASED";
export type CostRecord = { id: string; name: string; provider: string; category: CostCategory; amount: number; frequency: CostFrequency; source: CostSource; feature: string; active: boolean; usage?: number | null; periodStart: string; notes?: string | null };
export type CostSummary = { currentMonth: number; estimatedMonthEnd: number; today: number; last7Days: number; last30Days: number; revenue: number; estimatedNet: number | null; costPerCustomer: number | null; costPerPurchase: number | null; costPerRevenueDollar: number | null; byCategory: Record<string, number>; byFeature: Record<string, number>; budget: number | null; budgetPercent: number | null; alerts: string[] };

const monthlyMultiplier: Record<CostFrequency, number> = { ONE_TIME: 1, DAILY: 30, WEEKLY: 4.345, MONTHLY: 1, YEARLY: 1 / 12, USAGE_BASED: 1 };
export function normalizeMonthlyCost(record: Pick<CostRecord, "amount" | "frequency">) { return Math.max(0, Number(record.amount || 0)) * monthlyMultiplier[record.frequency]; }
export function buildCostSummary(records: CostRecord[], input: { revenue?: number; customers?: number; purchases?: number; budget?: number | null } = {}): CostSummary { const byCategory: Record<string, number> = {}; const byFeature: Record<string, number> = {}; let total = 0; for (const record of records.filter((item) => item.active)) { const monthly = normalizeMonthlyCost(record); total += monthly; byCategory[record.category] = (byCategory[record.category] || 0) + monthly; byFeature[record.feature] = (byFeature[record.feature] || 0) + monthly; } const revenue = Number(input.revenue || 0); const budget = input.budget === undefined ? null : input.budget; const budgetPercent = budget && budget > 0 ? total / budget * 100 : null; const alerts = budgetPercent !== null && budgetPercent >= 100 ? ["Monthly cost budget has been exceeded."] : budgetPercent !== null && budgetPercent >= 75 ? ["Monthly cost budget is approaching its configured threshold."] : []; return { currentMonth: total, estimatedMonthEnd: total, today: total / 30, last7Days: total / 30 * 7, last30Days: total, revenue, estimatedNet: revenue ? revenue - total : null, costPerCustomer: input.customers ? total / input.customers : null, costPerPurchase: input.purchases ? total / input.purchases : null, costPerRevenueDollar: revenue > 0 ? total / revenue : null, byCategory, byFeature, budget, budgetPercent, alerts }; }
export function detectCostSpike(previous: number, current: number, multiplier = 3) { return previous > 0 && current >= previous * multiplier; }

export async function getCostRecords(): Promise<CostRecord[]> { const credentials = serviceCredentials(); if (!credentials) return []; const [providerResponse, entryResponse] = await Promise.all([fetch(`${credentials.url}/rest/v1/cost_providers?select=id,category,provider,feature,fixed_monthly,usage_monthly,active,manual_entry&active=eq.true`, { cache: "no-store", headers: serviceHeaders(credentials) }).catch(() => null), fetch(`${credentials.url}/rest/v1/cost_entries?select=id,name,provider,category,feature,amount,frequency,source,active,period_start,notes&active=eq.true&order=created_at.desc`, { cache: "no-store", headers: serviceHeaders(credentials) }).catch(() => null)]); const providers = providerResponse?.ok ? await providerResponse.json() as Array<Record<string, unknown>> : []; const entries = entryResponse?.ok ? await entryResponse.json() as Array<Record<string, unknown>> : []; return [...providers.map((row) => ({ id: `provider:${String(row.id)}`, name: String(row.category), provider: String(row.provider), category: String(row.category).toUpperCase().replaceAll(" ", "_") as CostCategory, amount: Number(row.fixed_monthly || 0) + Number(row.usage_monthly || 0), frequency: "MONTHLY" as const, source: row.manual_entry ? "MANUAL" as const : "PROVIDER_API" as const, feature: String(row.feature || "OTHER"), active: row.active !== false, periodStart: new Date().toISOString() })), ...entries.map((row) => ({ id: `entry:${String(row.id)}`, name: String(row.name), provider: String(row.provider), category: String(row.category).toUpperCase().replaceAll(" ", "_") as CostCategory, amount: Number(row.amount || 0), frequency: String(row.frequency || "MONTHLY") as CostFrequency, source: String(row.source || "MANUAL") as CostSource, feature: String(row.feature || "OTHER"), active: row.active !== false, periodStart: String(row.period_start || new Date().toISOString()), notes: row.notes ? String(row.notes) : null }))]; }
