import { NextRequest, NextResponse } from "next/server";
import { adminSessionCookie, auditAdminEvent, getAdminBySession } from "@/lib/admin-auth";
import { serviceCredentials, serviceHeaders } from "@/lib/api-user";
import { getVerticalCatalog } from "@/lib/commerce/catalog";
import { safeStoreDestination } from "@/lib/commerce/validation";
import { extractClientIp } from "@/lib/security";
import type { CatalogEntry, CatalogSettings } from "@/lib/commerce/types";
const categories = new Set(["Merch", "Audio", "Video", "Painting", "News", "Event", "General"]); const statuses = new Set(["draft", "scheduled", "published", "expired", "archived"]);
export async function POST(request: NextRequest) { const admin = await getAdminBySession(request.cookies.get(adminSessionCookie)?.value); if (!admin || admin.role !== "ADMIN" || !admin.two_factor_required) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const service = serviceCredentials(); if (!service) return NextResponse.json({ error: "Catalog database unavailable." }, { status: 503 }); const body = await request.json().catch(() => ({})) as { action?: string; entry?: CatalogEntry; settings?: CatalogSettings }; const headers = serviceHeaders(service); if (body.action === "save-settings") { const settings = body.settings; if (!settings || !Number.isFinite(settings.speedSeconds)) return NextResponse.json({ error: "Invalid reel settings." }, { status: 400 }); const safeSettings = { speed_seconds: Math.max(12, Math.min(90, Math.round(settings.speedSeconds))), paused: Boolean(settings.paused), updated_by: admin.id, updated_at: new Date().toISOString() }; const response = await fetch(`${service.url}/rest/v1/vertical_catalog_settings?id=eq.primary`, { method: "PATCH", headers, body: JSON.stringify(safeSettings) }); if (!response.ok) return NextResponse.json({ error: "Reel settings were rejected." }, { status: 422 }); await auditAdminEvent({ adminUserId: admin.id, eventType: "admin_catalog_settings", ipAddress: extractClientIp(request.headers), userAgent: request.headers.get("user-agent") || "unknown", metadata: safeSettings }); const data = await getVerticalCatalog(true); return NextResponse.json({ ok: true, settings: data.settings }); } const entry = body.entry; if (!entry || !categories.has(entry.category) || !statuses.has(entry.status)) return NextResponse.json({ error: "Invalid catalog entry." }, { status: 400 }); const destination = entry.destinationUrl ? safeStoreDestination(entry.destinationUrl) : null; if (entry.destinationUrl && !destination) return NextResponse.json({ error: "Destination must be an internal path or approved HTTPS URL." }, { status: 400 }); let response: Response;
  if (body.action === "delete") response = await fetch(`${service.url}/rest/v1/vertical_catalog_entries?id=eq.${entry.id}&status=neq.published`, { method: "DELETE", headers });
  else if (body.action === "move-up" || body.action === "move-down") response = await fetch(`${service.url}/rest/v1/rpc/reorder_catalog_entry`, { method: "POST", headers, body: JSON.stringify({ p_entry_id: entry.id, p_direction: body.action === "move-up" ? -1 : 1 }) });
  else { const row = { title: entry.title.slice(0, 160), description: entry.description.slice(0, 2000), category: entry.category, image_url: entry.imageUrl, display_date: entry.displayDate.slice(0, 120), destination_url: destination, action_label: entry.actionLabel?.slice(0, 80) || null, status: entry.status, pinned: entry.pinned, sort_order: entry.sortOrder, publish_at: entry.publishAt, expires_at: entry.expiresAt, updated_by: admin.id, updated_at: new Date().toISOString() }; response = body.action === "create" ? await fetch(`${service.url}/rest/v1/vertical_catalog_entries`, { method: "POST", headers, body: JSON.stringify(row) }) : await fetch(`${service.url}/rest/v1/vertical_catalog_entries?id=eq.${entry.id}`, { method: "PATCH", headers, body: JSON.stringify(row) }); }
  if (!response.ok) return NextResponse.json({ error: "Catalog change rejected." }, { status: 422 }); await auditAdminEvent({ adminUserId: admin.id, eventType: `admin_catalog_${body.action || "save"}`, ipAddress: extractClientIp(request.headers), userAgent: request.headers.get("user-agent") || "unknown", metadata: { entryId: entry.id, category: entry.category } }); const data = await getVerticalCatalog(true); return NextResponse.json({ ok: true, entries: data.entries, settings: data.settings }); }
