import { randomUUID } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { getApiUser, serviceCredentials, serviceHeaders } from "@/lib/api-user";
import { getPaintingAuctions } from "@/lib/auctions/catalog";
import { extractClientIp } from "@/lib/security";
import { normalizeShippingAddress } from "@/lib/commerce/validation";
import { recordVerifiedAdminEarning } from "@/lib/admin-earnings";
const limits = new Map<string, { count: number; resetAt: number }>(); function limited(key: string) { const now = Date.now(); const value = limits.get(key); if (!value || value.resetAt < now) { limits.set(key, { count: 1, resetAt: now + 60_000 }); return false; } value.count += 1; return value.count > 20; }
export async function GET() { return NextResponse.json(await getPaintingAuctions(false)); }
export async function POST(request: NextRequest) { const user = await getApiUser(request); if (!user) return NextResponse.json({ code: "AUTH_REQUIRED", message: "Sign in before bidding or watching an auction." }, { status: 401 }); const service = serviceCredentials(); if (!service) return NextResponse.json({ code: "AUCTIONS_UNAVAILABLE", message: "Auction services are not connected." }, { status: 503 }); if (limited(`${user.id}:${extractClientIp(request.headers)}`)) return NextResponse.json({ code: "RATE_LIMITED", message: "Too many auction actions. Wait and retry." }, { status: 429 }); const body = await request.json().catch(() => ({})) as { action?: string; auctionId?: string; amount?: number; idempotencyKey?: string; shippingAddress?: unknown }; const headers = serviceHeaders(service); const key = String(request.headers.get("idempotency-key") || body.idempotencyKey || randomUUID()).slice(0, 120);
  if (body.action === "watch") { const response = await fetch(`${service.url}/rest/v1/painting_watchlist`, { method: "POST", headers: serviceHeaders(service, "resolution=merge-duplicates,return=minimal"), body: JSON.stringify({ user_id: user.id, auction_id: body.auctionId }) }); return response.ok ? NextResponse.json({ ok: true }) : NextResponse.json({ message: "Watchlist update failed." }, { status: 422 }); }
  if (body.action === "winner-address") { const address = normalizeShippingAddress(body.shippingAddress); if (!address) return NextResponse.json({ code: "SHIPPING_REQUIRED", message: "Complete the winner delivery address." }, { status: 400 }); const response = await fetch(`${service.url}/rest/v1/rpc/save_painting_winner_address`, { method: "POST", headers, body: JSON.stringify({ p_user_id: user.id, p_auction_id: body.auctionId, p_shipping_address: address }) }); return response.ok ? NextResponse.json({ ok: true }) : NextResponse.json({ code: "NOT_WINNER", message: "No eligible winning order was found for this account." }, { status: 403 }); }
  const rpc = body.action === "buy-now" ? "buy_now_painting" : body.action === "bid" ? "place_painting_bid" : null; if (!rpc) return NextResponse.json({ message: "Unsupported auction action." }, { status: 400 }); const amount = Number(body.amount); if (rpc === "place_painting_bid" && (!Number.isSafeInteger(amount) || amount < 1)) return NextResponse.json({ code: "INVALID_BID", message: "Enter a valid whole-coin bid." }, { status: 400 }); const address = rpc === "buy_now_painting" ? normalizeShippingAddress(body.shippingAddress) : null; if (rpc === "buy_now_painting" && !address) return NextResponse.json({ code: "SHIPPING_REQUIRED", message: "Complete the delivery address before Buy Now." }, { status: 400 }); const response = await fetch(`${service.url}/rest/v1/rpc/${rpc}`, { method: "POST", headers, body: JSON.stringify({ p_user_id: user.id, p_auction_id: body.auctionId, ...(rpc === "place_painting_bid" ? { p_amount: amount } : { p_shipping_address: address }), p_idempotency_key: key }) }).catch(() => null); if (!response?.ok) { const detail = await response?.text().catch(() => "") || ""; const code = ["AUCTION_CLOSED", "BID_TOO_LOW", "INSUFFICIENT_AVAILABLE_COINS", "DUPLICATE_ACTION", "PRODUCT_UNAVAILABLE"].find((value) => detail.includes(value)) || "AUCTION_ACTION_FAILED"; return NextResponse.json({ code, message: "The auction action was not accepted. No unapproved wallet change was made." }, { status: 409 }); } const result = await response.json() as Record<string, unknown>; if (rpc === "buy_now_painting") { await recordVerifiedAdminEarning({ category: "painting", sourceType: "painting_order", sourceId: String(result.orderId || result.order_id || key), amountMinor: Math.max(0, Math.floor(amount * 25)) }); } return NextResponse.json({ ok: true, result }); }
