"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import EmergencyMaintenancePanel from "@/components/admin/EmergencyMaintenancePanel";

type Row = Record<string, unknown>;
type Data = { configured?: boolean; error?: string; products?: Row[]; reservations?: Row[]; inventoryEvents?: Row[]; templates?: Row[]; emailJobs?: Row[]; policies?: Row[]; announcements?: Row[]; audits?: Row[]; analytics?: Row[]; maintenance?: Row | null; metrics?: Record<string, number> };
const tabs = ["overview", "inventory", "email", "notifications", "policies", "kill-switch", "audit", "analytics"] as const;

function count(events: Row[], type: string) { return events.filter((event) => event.event_type === type).length; }

export default function AdminPrelaunchManager() {
  const [data, setData] = useState<Data>({});
  const [tab, setTab] = useState<(typeof tabs)[number]>("overview");
  const [status, setStatus] = useState("Loading operations data...");
  const [search, setSearch] = useState("");
  const [selectedTemplate, setSelectedTemplate] = useState("");

  const refresh = useCallback(async () => {
    const response = await fetch("/api/admin/prelaunch", { cache: "no-store" }).catch(() => null);
    const payload = response ? await response.json() as Data : { error: "Operations data could not be loaded." };
    setData(payload); setStatus(payload.error || "");
    if (!selectedTemplate && payload.templates?.[0]) setSelectedTemplate(String(payload.templates[0].template_key || ""));
  }, [selectedTemplate]);
  useEffect(() => { void refresh(); }, [refresh]);

  async function submit(action: string, body: Row) {
    setStatus("Saving...");
    const response = await fetch("/api/admin/prelaunch", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...body }) });
    if (action === "audit-export" && response.ok) {
      const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = "xmf-admin-audit.csv"; link.click(); URL.revokeObjectURL(url); setStatus("Audit export created."); return;
    }
    const payload = await response.json().catch(() => ({})) as { error?: string };
    setStatus(payload.error || "Saved."); if (response.ok) await refresh();
  }

  const analytics = data.analytics || [];
  const metrics = data.metrics || {};
  const filteredAudits = useMemo(() => (data.audits || []).filter((item) => `${item.event_type} ${item.admin_user_id} ${JSON.stringify(item.metadata)}`.toLowerCase().includes(search.toLowerCase())), [data.audits, search]);
  const template = (data.templates || []).find((item) => item.template_key === selectedTemplate);
  const activeReservations = (data.reservations || []).reduce((sum, item) => sum + Number(item.quantity || 0), 0);
  const lowStock = (data.products || []).filter((item) => Number(item.inventory_quantity || 0) <= Number(item.low_stock_threshold || 0)).length;

  return <section className="admin-prelaunch">
    <nav className="admin-prelaunch-tabs" aria-label="Pre-launch sections">{tabs.map((item) => <button type="button" className={tab === item ? "is-active" : ""} onClick={() => setTab(item)} key={item}>{item === "kill-switch" ? "Kill Switch" : item}</button>)}</nav>
    <p className="admin-form-status" role="status">{status}</p>

    {tab === "overview" ? <div className="admin-dashboard-widgets">
      <article className="admin-dashboard-widget" data-state={data.configured ? "green" : "red"}><span>Operations database</span><strong>{data.configured ? "Connected" : "Unconfigured"}</strong><small>Additive schema, RLS, and queues</small></article>
      <article className="admin-dashboard-widget" data-state={lowStock ? "yellow" : "green"}><span>Low stock</span><strong>{lowStock}</strong><small>{activeReservations} units currently reserved</small></article>
      <article className="admin-dashboard-widget" data-state={(data.emailJobs || []).some((job) => job.status === "failed") ? "red" : "green"}><span>Email queue</span><strong>{(data.emailJobs || []).length}</strong><small>Recent queued and delivered jobs</small></article>
      <article className="admin-dashboard-widget" data-state="green"><span>Notifications</span><strong>{(data.announcements || []).length}</strong><small>Saved public announcements</small></article>
      <article className="admin-dashboard-widget" data-state="green"><span>Audit evidence</span><strong>{(data.audits || []).length}</strong><small>Recent protected admin actions</small></article>
      <article className="admin-dashboard-widget" data-state="green"><span>Analytics events</span><strong>{analytics.length}</strong><small>Privacy-conscious recent events</small></article>
    </div> : null}

    {tab === "inventory" ? <div className="admin-ops-grid">{(data.products || []).map((product) => <article className="admin-ops-card" key={String(product.id)}><h2>{String(product.title)}</h2><p>{String(product.sku || "No SKU")} · {Number(product.inventory_quantity || 0)} available</p><p>{(data.reservations || []).filter((item) => item.product_id === product.id).reduce((sum, item) => sum + Number(item.quantity || 0), 0)} reserved · low at {Number(product.low_stock_threshold || 0)}</p><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit("inventory-adjust", { productId: product.id, variantId: form.get("variantId") || null, delta: Number(form.get("delta")), reason: form.get("reason") }); }}><select name="variantId"><option value="">Base product</option>{(product.product_variants as Row[] || []).map((variant) => <option value={String(variant.id)} key={String(variant.id)}>{String(variant.sku)} · {Number(variant.inventory_quantity || 0)}</option>)}</select><input name="delta" type="number" placeholder="+/- quantity" required /><input name="reason" minLength={4} placeholder="Adjustment reason" required /><button className="primary" type="submit">Apply adjustment</button></form><details><summary>Public inventory settings</summary><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit("inventory-settings", { productId: product.id, lowStockThreshold: Number(form.get("lowStockThreshold")), restockAt: form.get("restockAt") || null, restockNotificationsEnabled: form.get("restockNotificationsEnabled") === "on", showExactInventory: form.get("showExactInventory") === "on" }); }}><label>Low-stock threshold<input name="lowStockThreshold" type="number" min={0} defaultValue={Number(product.low_stock_threshold || 0)} /></label><label>Restock date<input name="restockAt" type="datetime-local" /></label><label className="admin-check-row"><input name="restockNotificationsEnabled" type="checkbox" defaultChecked={product.restock_notifications_enabled === true} /> Restock requests enabled</label><label className="admin-check-row"><input name="showExactInventory" type="checkbox" defaultChecked={product.show_exact_inventory === true} /> Show exact counts publicly</label><button className="secondary" type="submit">Save stock settings</button></form></details></article>)}
      <section className="admin-ops-table"><h2>Inventory history</h2>{(data.inventoryEvents || []).map((event) => <p key={String(event.id)}><time>{new Date(String(event.created_at)).toLocaleString()}</time><strong>{String(event.event_type)}</strong><span>{Number(event.quantity_delta || 0) > 0 ? "+" : ""}{Number(event.quantity_delta || 0)} → {Number(event.quantity_after || 0)}</span><small>{String(event.reason)}</small></p>)}</section></div> : null}

    {tab === "email" ? <div className="admin-ops-grid"><section className="admin-ops-card"><h2>Email Templates</h2><label>Template<select value={selectedTemplate} onChange={(event) => setSelectedTemplate(event.target.value)}>{(data.templates || []).map((item) => <option value={String(item.template_key)} key={String(item.template_key)}>{String(item.template_key)}</option>)}</select></label>{template ? <form key={String(template.template_key)} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit("template-save", { templateKey: template.template_key, subject: form.get("subject"), bodyText: form.get("bodyText"), buttonLabel: form.get("buttonLabel"), headerImageUrl: form.get("headerImageUrl"), enabled: form.get("enabled") === "on" }); }}><label>Subject<input name="subject" defaultValue={String(template.subject || "")} /></label><label>Body<textarea name="bodyText" defaultValue={String(template.body_text || "")} rows={8} /></label><label>Button label<input name="buttonLabel" defaultValue={String(template.button_label || "")} /></label><label>Header image URL<input name="headerImageUrl" defaultValue={String(template.header_image_url || "")} /></label><label className="admin-check-row"><input name="enabled" type="checkbox" defaultChecked={template.enabled !== false} /> Enabled</label><p>Approved variables: {(template.allowed_variables as string[] || []).map((item) => `{{${item}}}`).join(", ")}</p><button className="primary" type="submit">Save template</button><button className="secondary" type="button" onClick={() => void submit("email-test", { templateKey: template.template_key })}>Queue test</button></form> : null}</section><section className="admin-ops-table"><h2>Delivery log</h2>{(data.emailJobs || []).map((job) => <p key={String(job.id)}><time>{new Date(String(job.queued_at)).toLocaleString()}</time><strong>{String(job.template_key)}</strong><span>{String(job.status)}</span><small>{String(job.recipient_email)} · retry {Number(job.retry_count || 0)}</small></p>)}</section></div> : null}

    {tab === "notifications" ? <div className="admin-ops-grid"><section className="admin-ops-card"><h2>Create announcement</h2><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit("announcement-save", { ...Object.fromEntries(form), published: form.get("published") === "true" }); }}><label>Title<input name="title" required maxLength={180} /></label><label>Message<textarea name="message" required rows={5} /></label><label>Destination<input name="destinationUrl" placeholder="/live" /></label><label>Audience<select name="audience"><option value="all_visitors">All visitors</option><option value="customers">Customers</option><option value="purchasers">Purchasers</option><option value="admin_test">ADMIN test</option></select></label><label>Priority<select name="priority"><option>normal</option><option>high</option><option>critical</option><option>low</option></select></label><label className="admin-check-row"><input name="published" type="checkbox" value="true" /> Publish now</label><button className="primary" type="submit">Save announcement</button></form></section><section className="admin-ops-table"><h2>Announcement history</h2>{(data.announcements || []).map((item) => <p key={String(item.id)}><time>{new Date(String(item.created_at)).toLocaleString()}</time><strong>{String(item.title)}</strong><span>{item.published ? "Published" : "Draft"}</span><small>{String(item.audience)} · {String(item.priority)}</small></p>)}</section></div> : null}

    {tab === "policies" ? <div className="admin-ops-grid"><section className="admin-ops-card"><h2>Versioned policies</h2><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit("policy-save", { policyId: form.get("policyId"), languageCode: form.get("languageCode"), bodyText: form.get("bodyText"), status: form.get("status") }); }}><label>Document<select name="policyId">{(data.policies || []).map((policy) => <option value={String(policy.id)} key={String(policy.id)}>{String(policy.title)}</option>)}</select></label><label>Language code<input name="languageCode" defaultValue="en" pattern="[a-z]{2}(-[A-Z]{2})?" /></label><label>New version<textarea name="bodyText" minLength={40} rows={12} required /></label><label>Status<select name="status"><option value="draft">Save draft</option><option value="published">Publish now</option></select></label><p className="admin-warning">Publishing changes customer-facing legal text. Qualified legal review is required before launch.</p><button className="primary" type="submit">Create version</button></form></section><section className="admin-ops-table"><h2>Version history</h2>{(data.policies || []).map((policy) => <p key={String(policy.id)}><strong>{String(policy.title)}</strong><span>{(policy.policy_versions as Row[] || []).length} versions</span><small>{policy.requires_acceptance ? "Acceptance required" : "Reference policy"}</small></p>)}</section></div> : null}

    {tab === "kill-switch" ? <EmergencyMaintenancePanel compact /> : null}

    {tab === "audit" ? <section className="admin-ops-table"><header><div><h2>Admin Audit Log</h2><p>Append-only operational evidence. Sensitive addresses are masked in this broad view.</p></div><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Filter actions" /><button className="secondary" type="button" onClick={() => void submit("audit-export", {})}>Export CSV</button></header>{filteredAudits.map((item) => <p key={String(item.id)}><time>{new Date(String(item.created_at)).toLocaleString()}</time><strong>{String(item.event_type)}</strong><span>{String(item.ip_address || "")}</span><small>{JSON.stringify(item.metadata)}</small></p>)}</section> : null}

    {tab === "analytics" ? <div className="admin-analytics"><section className="admin-dashboard-widgets"><article className="admin-dashboard-widget" data-state="green"><span>Registered customers</span><strong>{metrics.registeredCustomers || 0}</strong><small>{metrics.uniquePurchasers || 0} unique purchasers</small></article><article className="admin-dashboard-widget" data-state="green"><span>Completed orders</span><strong>{metrics.completedOrders || 0}</strong><small>{metrics.coinsSpent || 0} coins spent</small></article><article className="admin-dashboard-widget" data-state="green"><span>Average order</span><strong>{metrics.averageOrderCoins || 0}</strong><small>Coins per completed order</small></article><article className="admin-dashboard-widget" data-state="green"><span>Searches</span><strong>{count(analytics, "search")}</strong><small>{analytics.filter((item) => item.event_type === "search" && Number(item.result_count) === 0).length} no-result searches</small></article><article className="admin-dashboard-widget" data-state="green"><span>Result clicks</span><strong>{count(analytics, "search_result_click")}</strong><small>Tracked without raw IP storage</small></article><article className="admin-dashboard-widget" data-state="green"><span>Page events</span><strong>{analytics.length}</strong><small>Recent capped event window</small></article><article className="admin-dashboard-widget" data-state="green"><span>Restock interest</span><strong>{metrics.restockRequests || 0}</strong><small>{metrics.fulfilledRestocks || 0} fulfilled</small></article><article className="admin-dashboard-widget" data-state="green"><span>Paintings</span><strong>{metrics.paintingsSold || 0} sold</strong><small>{metrics.paintingsAvailable || 0} available or scheduled</small></article></section><section className="admin-ops-table"><h2>No Results Searches</h2>{analytics.filter((item) => item.event_type === "search" && Number(item.result_count) === 0).slice(0, 50).map((item, index) => <p key={`${String(item.occurred_at)}:${index}`}><time>{new Date(String(item.occurred_at)).toLocaleString()}</time><strong>{String(item.search_term || "(empty)")}</strong><span>{String(item.filter_value || "all")}</span></p>)}</section></div> : null}
  </section>;
}
