"use client";

import Image from "next/image";
import { useCallback, useState } from "react";
import ImagePicker from "@/components/admin/media/ImagePicker";
import type { MediaAsset } from "@/lib/media/types";
import type { Clips4SaleItem, ExternalPlatformSettings } from "@/lib/external-platforms";

export default function AdminExternalPlatforms({ initialSettings, initialClips, configured }: { initialSettings: ExternalPlatformSettings; initialClips: Clips4SaleItem[]; configured: boolean }) {
  const [settings, setSettings] = useState(initialSettings); const [clips, setClips] = useState(initialClips); const [picker, setPicker] = useState<{ type: "fansly" | "clip"; id?: string } | null>(null); const [message, setMessage] = useState(configured ? "External platform settings connected." : "Preview settings shown until the external-platform migration is applied.");
  const closePicker = useCallback(() => setPicker(null), []);
  async function save(payload: unknown) { const response = await fetch("/api/admin/external-platforms", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => ({})) as { error?: string; settings?: ExternalPlatformSettings; clips?: Clips4SaleItem[] }; if (!response.ok) { setMessage(result.error || "Save failed."); return; } if (result.settings) setSettings(result.settings); if (result.clips) setClips(result.clips); setMessage("External platform settings saved and audit logged."); }
  function selectImage(asset: MediaAsset) { if (!picker) return; if (picker.type === "fansly") setSettings((value) => ({ ...value, fanslyHeroImage: asset.publicUrl })); else setClips((items) => items.map((item) => item.id === picker.id ? { ...item, thumbnailUrl: asset.publicUrl } : item)); setPicker(null); }
  return <section className="admin-commerce-panel admin-external-platforms"><header><div><p className="kicker">ADMIN · EXTERNAL PLATFORMS</p><h2>Fansly & Clips4Sale</h2><p>Public copy, exact HTTPS destinations, visibility, ordering, and shared Media Library artwork.</p></div></header><p role="status">{message}</p>
    <article className="admin-platform-card"><h3>Fansly</h3><label>Displayed handle<input value={settings.fanslyHandle} onChange={(event) => setSettings({ ...settings, fanslyHandle: event.target.value })} /></label><label>Biography<textarea rows={6} value={settings.fanslyBiography} onChange={(event) => setSettings({ ...settings, fanslyBiography: event.target.value })} /></label><label>Fansly HTTPS URL<input type="url" value={settings.fanslyUrl} onChange={(event) => setSettings({ ...settings, fanslyUrl: event.target.value })} /></label><label>Button label<input value={settings.fanslyButtonLabel} onChange={(event) => setSettings({ ...settings, fanslyButtonLabel: event.target.value })} /></label><label className="check-row"><input type="checkbox" checked={settings.fanslyEnabled} onChange={(event) => setSettings({ ...settings, fanslyEnabled: event.target.checked })} />Public button enabled</label><div className="admin-platform-image"><Image src={settings.fanslyHeroImage} alt="Fansly hero preview" width={360} height={220} /><button className="secondary" type="button" onClick={() => setPicker({ type: "fansly" })}>Choose hero from Media Library</button></div><div className="admin-audio-actions"><a className="secondary admin-link-button" href={settings.fanslyUrl} target="_blank" rel="noopener noreferrer">Preview destination</a><button className="primary" type="button" onClick={() => void save({ action: "save-settings", settings })}>Save Fansly</button></div></article>
    <article className="admin-platform-card"><h3>Clips4Sale</h3><label>Store biography<textarea rows={6} value={settings.clipsBiography} onChange={(event) => setSettings({ ...settings, clipsBiography: event.target.value })} /></label><label>Full store HTTPS URL<input type="url" value={settings.clipsStoreUrl} onChange={(event) => setSettings({ ...settings, clipsStoreUrl: event.target.value })} /></label><label>Store button label<input value={settings.clipsButtonLabel} onChange={(event) => setSettings({ ...settings, clipsButtonLabel: event.target.value })} /></label><button className="primary" type="button" onClick={() => void save({ action: "save-settings", settings })}>Save store settings</button></article>
    <div className="admin-clip-list">{clips.map((clip, index) => <article key={clip.id}><div className="admin-platform-image"><Image src={clip.thumbnailUrl} alt={clip.title} width={320} height={180} /><button className="secondary" type="button" onClick={() => setPicker({ type: "clip", id: clip.id })}>Choose thumbnail</button></div><label>Title<input value={clip.title} onChange={(event) => setClips((items) => items.map((item) => item.id === clip.id ? { ...item, title: event.target.value } : item))} /></label><label>Description<textarea rows={3} value={clip.description} onChange={(event) => setClips((items) => items.map((item) => item.id === clip.id ? { ...item, description: event.target.value } : item))} /></label><label>Exact product URL<input type="url" value={clip.productUrl || ""} placeholder="https://www.clips4sale.com/...exact-product" onChange={(event) => setClips((items) => items.map((item) => item.id === clip.id ? { ...item, productUrl: event.target.value || null } : item))} /></label><label>Duration<input value={clip.duration} onChange={(event) => setClips((items) => items.map((item) => item.id === clip.id ? { ...item, duration: event.target.value } : item))} /></label><label>Order<input type="number" min={1} value={clip.sortOrder} onChange={(event) => setClips((items) => items.map((item) => item.id === clip.id ? { ...item, sortOrder: Number(event.target.value) } : item))} /></label><div className="admin-switch-grid"><label><input type="checkbox" checked={clip.published} onChange={(event) => setClips((items) => items.map((item) => item.id === clip.id ? { ...item, published: event.target.checked } : item))} />Published</label><label><input type="checkbox" checked={clip.featured} onChange={(event) => setClips((items) => items.map((item) => item.id === clip.id ? { ...item, featured: event.target.checked } : item))} />Featured</label></div><div className="admin-audio-actions"><button className="secondary" type="button" disabled={index === 0} onClick={() => { const copy = [...clips]; [copy[index - 1], copy[index]] = [copy[index], copy[index - 1]]; setClips(copy.map((item, position) => ({ ...item, sortOrder: position + 1 }))); }}>Move up</button><button className="primary" type="button" onClick={() => void save({ action: "save-clip", clip })}>Save clip</button></div></article>)}</div>
    <ImagePicker open={Boolean(picker)} category="promotional" title="Choose promotional image" onClose={closePicker} onSelect={selectImage} />
  </section>;
}

