"use client";

import { useState } from "react";
import type { InfrastructureServiceStatus, InfrastructureSnapshot, JobRecord } from "@/lib/infrastructure";
import { formatDateTimeInZone, platformTimeZone } from "@/lib/timezone";

function statusClass(status: string) { return status === "HEALTHY" || status === "SANDBOX" ? "green" : status === "DEGRADED" || status === "ACTION REQUIRED" ? "yellow" : status === "OFFLINE" ? "red" : "disabled"; }

export default function InfrastructureCenter({ initialSnapshot, initialJobs }: { initialSnapshot: InfrastructureSnapshot; initialJobs: JobRecord[] }) {
  const [snapshot, setSnapshot] = useState(initialSnapshot);
  const [jobs, setJobs] = useState(initialJobs);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);

  async function refresh() { setBusy(true); const response = await fetch("/api/admin/infrastructure", { cache: "no-store" }).catch(() => null); const data = response?.ok ? await response.json() : null; if (data) { setSnapshot(data.snapshot); setJobs(data.jobs); setMessage("Infrastructure checks refreshed."); } else setMessage("Infrastructure checks could not be refreshed."); setBusy(false); }
  async function jobAction(action: "retry-job" | "cancel-job", job: JobRecord) { if (action === "cancel-job" && !window.confirm("Cancel this queued job? Its record will remain available for audit.")) return; setBusy(true); const response = await fetch("/api/admin/infrastructure", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, jobId: job.id, confirmed: true }) }).catch(() => null); const data = response?.ok ? await response.json() : null; if (data) { setSnapshot(data.snapshot); setJobs(data.jobs); setMessage(`Job ${job.id.slice(0, 8)} ${action === "retry-job" ? "queued for retry" : "canceled"}.`); } else setMessage("The job action was not completed."); setBusy(false); }
  async function flagAction(name: string, state: "ON" | "OFF") { setBusy(true); const response = await fetch("/api/admin/infrastructure", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "set-feature-flag", name, state }) }).catch(() => null); const data = response?.ok ? await response.json() : null; if (data) { setSnapshot(data.snapshot); setJobs(data.jobs); setMessage(`${name} is now ${state}.`); } else setMessage("The feature flag change was not completed."); setBusy(false); }

  return <>
    <section className="admin-auth-panel infrastructure-summary"><div><p className="kicker">ENVIRONMENT</p><h2>{snapshot.environment}</h2><p>Local adapters remain safe for development. Production requires approved external providers and real health checks.</p></div><div className="admin-quick-actions"><button className="primary" type="button" disabled={busy} onClick={() => void refresh()}>{busy ? "Checking..." : "Refresh checks"}</button><a className="secondary admin-link-button" href="/admin/system/live-diagnostics">Live diagnostics</a><span>Release <strong>{snapshot.release.version}</strong></span></div></section>
    <section className="admin-auth-panel"><header><div><p className="kicker">PROVIDER CONFIGURATION · BATCH 1</p><h2>External service readiness</h2><p>Configuration status is derived from server environment names only. Credentials are never shown, and no external operation is performed by this summary.</p></div></header><div className="admin-control-grid infrastructure-service-grid">{snapshot.providerConfiguration.map((provider) => <article className="admin-control-card" data-state={statusClass(provider.state === "CONFIGURED" ? "HEALTHY" : provider.state === "PARTIAL" ? "DEGRADED" : provider.state === "ERROR" ? "OFFLINE" : "NOT CONFIGURED")} key={provider.id}><div className="admin-control-top"><div><p className="kicker">{provider.id}</p><h2>{provider.label}</h2></div><span className={`admin-health ${statusClass(provider.state === "CONFIGURED" ? "HEALTHY" : provider.state === "PARTIAL" ? "DEGRADED" : provider.state === "ERROR" ? "OFFLINE" : "NOT CONFIGURED")}`}>{provider.state}</span></div><p>{provider.detail}</p>{provider.id === "email" ? <p><strong>Mode:</strong> {provider.mode || "disabled"} · <strong>From:</strong> {provider.senderConfigured ? "configured" : "not configured"} · <strong>Sender verification:</strong> {provider.senderVerified === true ? "verified" : provider.senderVerified === false ? "required" : "pending"}</p> : null}<p><strong>Last successful health:</strong> {provider.lastSuccessfulHealthCheck || "UNVERIFIED"}</p></article>)}</div></section>
    <section className="admin-control-grid infrastructure-service-grid" aria-label="Infrastructure services">{snapshot.services.map((service) => <InfrastructureService key={service.id} service={service} />)}</section>
    <section className="admin-dashboard-widgets infrastructure-metrics"><Metric label="Queue depth" value={snapshot.queue.depth} detail={`Running ${snapshot.queue.running} · Failed ${snapshot.queue.failed}`} /><Metric label="Shared cache" value={snapshot.cache.status} detail={`${snapshot.cache.provider} · ${snapshot.cache.shared ? "distributed" : "process-local"} · ${snapshot.cache.latencyMs ?? "-"}ms`} /><Metric label="Private signing" value={snapshot.storage.privateSigning ? "Ready" : "Not configured"} detail="Required for protected media delivery" /><Metric label="Backups" value={snapshot.backup.database} detail={`PITR ${snapshot.backup.pitr} · Restore ${snapshot.backup.lastRestoreTest ? "recorded" : "unverified"}`} /><Metric label="Rollback" value={snapshot.release.rollbackReady ? "Ready" : "Unverified"} detail="Provider-native rollback remains preferred" /></section>
    <section className="admin-auth-panel"><header><div><p className="kicker">BACKUPS</p><h2>Backup and restore readiness</h2><p>Restore tests are designed for SANDBOX or STAGING and never overwrite Production. No backup success is claimed without an approved provider check.</p></div></header><div className="admin-dashboard-widgets"><Metric label="Database" value={snapshot.backup.database} detail={`Last backup ${snapshot.backup.lastBackup || "unverified"}`} /><Metric label="Media" value={snapshot.backup.media} detail={`Provider ${snapshot.backup.provider}`} /><Metric label="PITR" value={snapshot.backup.pitr} detail="Point-in-time recovery status" /><Metric label="Restore test" value={snapshot.backup.lastRestoreTest ? "Recorded" : "Not verified"} detail="Sandbox/Staging workflow only" /></div><button className="secondary" type="button" disabled title="Connect an approved backup provider before running a restore test">Run restore test in Sandbox/Staging</button></section>
    <section className="admin-auth-panel"><header><div><p className="kicker">FEATURE FLAGS</p><h2>Controlled rollout</h2><p>Admin-only, process-local controls until a durable provider is connected. Production cannot enable a flag through this local adapter.</p></div></header><div className="backbone-row">{snapshot.featureFlags.map((flag) => <div className="backbone-panel" key={flag.name}><strong>{flag.name}</strong><span>{flag.state}</span><small>{flag.persistence} · changed by {flag.updatedBy}</small><div className="admin-quick-actions"><button className="secondary" type="button" disabled={busy || flag.state === "ON"} onClick={() => void flagAction(flag.name, "ON")}>On</button><button className="secondary" type="button" disabled={busy || flag.state === "OFF"} onClick={() => void flagAction(flag.name, "OFF")}>Off</button></div></div>)}</div></section>
    <section className="admin-auth-panel"><header><div><p className="kicker">SECURITY EDGE</p><h2>Protection readiness</h2><p>These controls are reported honestly and do not claim Cloudflare, Turnstile, or managed WAF coverage without a configured provider check.</p></div></header><div className="admin-dashboard-widgets"><Metric label="WAF" value={snapshot.security.waf} detail="External edge probe required" /><Metric label="DDoS" value={snapshot.security.ddos} detail="Provider configuration required" /><Metric label="Bot protection" value={snapshot.security.botProtection} detail="Turnstile-compatible hook prepared" /><Metric label="Managed rate limiting" value={snapshot.security.managedRateLimit} detail="Local request controls active" /></div></section>
    <section className="admin-auth-panel"><header><div><p className="kicker">BACKGROUND JOBS</p><h2>Queue operations</h2><p>Jobs are provider-neutral and idempotent. Financial and fulfillment work must verify provider state before retrying.</p></div></header>{jobs.length ? <div className="printify-table-wrap"><table><thead><tr><th>Type</th><th>Status</th><th>Environment</th><th>Retries</th><th>Created</th><th>Actions</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id}><td>{job.type}</td><td>{job.status}</td><td>{job.environment}</td><td>{job.retryCount}</td><td>{formatDateTimeInZone(new Date(job.createdAt), platformTimeZone)}</td><td>{["FAILED", "ACTION REQUIRED"].includes(job.status) ? <button className="secondary" type="button" disabled={busy} onClick={() => void jobAction("retry-job", job)}>Retry</button> : null}{["QUEUED", "RETRYING"].includes(job.status) ? <button className="secondary danger" type="button" disabled={busy} onClick={() => void jobAction("cancel-job", job)}>Cancel</button> : null}</td></tr>)}</tbody></table></div> : <p>No background jobs are queued in this process. Persistent production workers are not configured.</p>}<p role="status">{message}</p></section>
    <section className="admin-auth-panel"><p className="kicker">BOUNDARIES</p><h2>Provider-neutral by design</h2><ul><li>Public assets and private media use separate delivery paths.</li><li>Local storage, queue, and cache are never marked production-ready.</li><li>Analytics, email, cache, and media failures must not interrupt checkout or live viewing.</li><li>Database, authentication, payment integrity, audit logs, and core security remain protected from optional switches.</li></ul></section>
  </>;
}

function InfrastructureService({ service }: { service: InfrastructureServiceStatus }) { return <article className="admin-control-card" data-state={statusClass(service.status)}><div className="admin-control-top"><div><p className="kicker">{service.id}</p><h2>{service.label}</h2></div><span className={`admin-health ${statusClass(service.status)}`}>{service.status}</span></div><p><strong>Provider:</strong> {service.provider}</p><p><strong>Last check:</strong> {formatDateTimeInZone(new Date(service.lastCheck), platformTimeZone)}</p><p>{service.health}</p>{service.errorState ? <small>{service.errorState}</small> : null}<div className="admin-switch-meta"><span>Feature<strong>{service.enabled ? "Available" : "Not configured"}</strong></span><span>Control<strong>{service.switchable ? "Optional" : "Protected"}</strong></span></div></article>; }
function Metric({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <article className="admin-dashboard-widget"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
