"use client";

import { useEffect, useState } from "react";

type Settings = { enabled: boolean; popupDelaySeconds: number; consentVersion: string; consentLifetimeDays: number; privacyPolicyUrl: string; cookiePolicyUrl: string; gpcSupport: boolean };
type Stats = { total: number; accepted: number; rejected: number; customized: number; analytics: number; gpc: number };
const initialSettings: Settings = { enabled: true, popupDelaySeconds: 46, consentVersion: "1.0", consentLifetimeDays: 180, privacyPolicyUrl: "/policies#privacy", cookiePolicyUrl: "/policies#cookies", gpcSupport: true };
const initialStats: Stats = { total: 0, accepted: 0, rejected: 0, customized: 0, analytics: 0, gpc: 0 };

export default function PrivacyConsentPanel() {
  const [settings, setSettings] = useState(initialSettings); const [stats, setStats] = useState(initialStats); const [message, setMessage] = useState("Loading privacy controls...");
  async function load() { const response = await fetch("/api/admin/privacy", { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (response.ok) { setSettings({ ...initialSettings, ...data.settings }); setStats({ ...initialStats, ...data.stats }); setMessage("Consent settings loaded."); } else setMessage(data.error || "Privacy settings could not load."); }
  useEffect(() => { void load(); }, []);
  async function save() { setMessage("Saving..."); const response = await fetch("/api/admin/privacy", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(settings) }); setMessage(response.ok ? "Privacy settings saved and audit logged." : "Privacy settings could not be saved."); }
  function sandbox(action: "reset" | "timer" | "accept" | "reject" | "customize" | "gpc") { localStorage.removeItem("xmf-cookie-consent"); if (action === "accept") localStorage.setItem("xmf-cookie-consent", JSON.stringify({ consentVersion: settings.consentVersion, necessary: true, analytics: true, functional: true, marketing: true, advertising: true, gpc: false, timestamp: new Date().toISOString() })); if (action === "reject") localStorage.setItem("xmf-cookie-consent", JSON.stringify({ consentVersion: settings.consentVersion, necessary: true, analytics: false, functional: false, marketing: false, advertising: false, gpc: false, timestamp: new Date().toISOString() })); if (action === "customize") localStorage.setItem("xmf-cookie-consent", JSON.stringify({ consentVersion: settings.consentVersion, necessary: true, analytics: true, functional: false, marketing: false, advertising: false, gpc: false, timestamp: new Date().toISOString() })); if (action === "gpc") localStorage.setItem("xmf-cookie-consent", JSON.stringify({ consentVersion: settings.consentVersion, necessary: true, analytics: false, functional: false, marketing: false, advertising: false, gpc: true, timestamp: new Date().toISOString() })); window.open("/sandbox?privacy-preview=1", "_blank", "noopener,noreferrer"); }
  return <section className="admin-commerce-panel privacy-admin-panel"><header><div><p className="kicker">PRIVACY &amp; COOKIES</p><h2>Consent controls</h2><p>Optional trackers remain blocked when this visible prompt is disabled. Necessary security and session technologies are never disabled here.</p></div><strong className={settings.enabled ? "health-green" : "health-yellow"}>{settings.enabled ? "ON" : "OFF"}</strong></header><div className="privacy-admin-grid"><label>Consent system<select value={settings.enabled ? "on" : "off"} onChange={(event) => setSettings({ ...settings, enabled: event.target.value === "on" })}><option value="on">On</option><option value="off">Off · optional stays blocked</option></select></label><label>Popup delay (seconds)<input type="number" min={5} max={3600} value={settings.popupDelaySeconds} onChange={(event) => setSettings({ ...settings, popupDelaySeconds: Number(event.target.value) })} /></label><label>Consent version<input value={settings.consentVersion} onChange={(event) => setSettings({ ...settings, consentVersion: event.target.value })} /></label><label>Consent lifetime (days)<input type="number" min={1} max={730} value={settings.consentLifetimeDays} onChange={(event) => setSettings({ ...settings, consentLifetimeDays: Number(event.target.value) })} /></label><label className="privacy-admin-check"><input type="checkbox" checked={settings.gpcSupport} onChange={(event) => setSettings({ ...settings, gpcSupport: event.target.checked })} /> Respect Global Privacy Control</label></div><div className="admin-quick-actions"><button className="primary" type="button" onClick={() => void save()}>Save privacy settings</button><a className="secondary admin-link-button" href={settings.privacyPolicyUrl}>Privacy Policy</a><a className="secondary admin-link-button" href={settings.cookiePolicyUrl}>Cookie Policy</a></div><h3>Consent statistics</h3><div className="admin-auth-grid privacy-admin-stats"><span>Total choices<strong>{stats.total}</strong></span><span>Accept all<strong>{stats.accepted}</strong></span><span>Reject all<strong>{stats.rejected}</strong></span><span>Customized<strong>{stats.customized}</strong></span><span>Analytics enabled<strong>{stats.analytics}</strong></span><span>GPC detected<strong>{stats.gpc}</strong></span></div><h3>Sandbox privacy tests</h3><div className="admin-quick-actions"><button className="secondary" type="button" onClick={() => sandbox("reset")}>Reset Consent</button><button className="secondary" type="button" onClick={() => sandbox("timer")}>Simulate 46 Seconds</button><button className="secondary" type="button" onClick={() => sandbox("accept")}>Accept</button><button className="secondary" type="button" onClick={() => sandbox("reject")}>Reject</button><button className="secondary" type="button" onClick={() => sandbox("customize")}>Customize</button><button className="secondary" type="button" onClick={() => sandbox("gpc")}>Simulate GPC</button></div><p role="status">{message}</p></section>;
}
